_static/theme_overrides.css
conf.py
introduction/features.rst
wallets/dashcore/privatesend-instantsend.rst

- Add table of PS tx types as shown in Dash Core
- Also enable table text wrapping

PrivateSend Transaction type info

---

introduction/information.rst

SSIA -- Signaling is a term most people don't grok. This should help.

Adding to the glossary: Signaling

---

masternodes/understanding.rst

Change from "valid set" (only non-banned MNs) to the full count of all registered MNs.
@codablock - look good?

Proof of Service Update

---

masternodes/setup-testnet.rst

Crypto teller v17links

---

developers/testnet.rst

Use URL for the faucet on the correct chain

V0.16.0/faucet update

---

masternodes/setup-testnet.rst

Save a manual step / chance for typo by automatically grabbing the username

docs: use $USER var to automatically insert username

---

introduction/features.rst

Updates tense, insert missing word, and simplify table

docs: minor wording change and fee table update

---

network/electrumx-server.rst

chore: fix heading underline

---

developers/integration.rst

fix: correct broken URL

---

governance/eight-steps.rst

Add mention of Dash Investment Foundation

---

conf.py

Update year and authors in copyright info

chore: update copyright for 2021

---

developers/insight.rst
masternodes/maintenance.rst
masternodes/setup-testnet.rst
masternodes/setup.rst
mining/p2pool.rst
wallets/dashcore/installation-linux.rst
wallets/dashcore/installation-macos.rst
wallets/dashcore/installation-windows.rst
wallets/electrum/installation.rst

Change download links to point to the newest version

chore: 0.17.0.3 update

---

developers/compiling.rst

Preview: https://dash-docs--104.org.readthedocs.build/en/104/developers/compiling.html

chore: update some outdated Core version references

---

developers/integration.rst

Based on #109 
https://dash-docs--114.org.readthedocs.build/en/114/developers/integration.html

docs: update integration page

---

governance/using.rst

Explains how to create and submit proposals via the Core wallet
Link to preview: https://dash-docs--115.org.readthedocs.build/en/115/governance/using.html#dash-core-wallet-console

feat: proposal creation via Core

---

developers/compiling.rst
governance/using.rst

gettext throws a warning otherwise - see https://github.com/sphinx-doc/sphinx/issues/3921
https://dash-docs--118.org.readthedocs.build/en

fix: duplicate explicit target names

---

governance/using.rst

Changes proposal fee references to match the amount in dashpay/dash#4241.
Preview: https://dash-docs--119.org.readthedocs.build/en/119/governance/using.html

chore: update proposal fee from 5 Dash -> 1

---

developers/compiling.rst

As requested by @PastaPastaPasta 
Preview: https://dash-docs--121.org.readthedocs.build/en/121/developers/compiling.html#build-process

chore: emphasize linux version to use for best results

---

mining/index.rst

docs: update list of ASIC resellers

---

requirements.txt

See https://github.com/readthedocs/readthedocs.org/issues/9037
Didn't see this issue on dashpay/docs yet, but did on my own fork

fix: pin jinja version

---

README.md
governance/index.rst
governance/understanding.rst
governance/using.rst
introduction/features.rst
introduction/information.rst

Turned "DGBB" to "DAO"
Preview: https://dash-docs--140.org.readthedocs.build/en/140/governance/index.html

Demobranchdocs

---

masternodes/maintenance.rst

Sentinel wasn't working after pulling from the repo resulted in changed dependencies.

chore: remember to update sentinel deps

---

masternodes/setup-testnet.rst

just small update to the release build for v18.0.1

update binary from RC4 to release

---

conf.py
requirements.txt

Found this while doing some research on RtD. 
See https://dash-docs--164.org.readthedocs.build/en/164/network/electrumx-server.html for example of operation

feat: add copy button for code snippets

---

wallets/dashcore/installation-linux.rst

Adding docs to add a Dash icon to Gnome/KDE launchers. How do I render a preview of this again?

docs: steps to add a linux desktop icon

---

conf.py
docs/user/index.rst
index.rst
requirements.txt

https://dash-docs--175.org.readthedocs.build/en/175/

feat: add sphinx-design extension and update main page

---

_static/css/pydata-overrides.css
conf.py

Use Dash blues and adjust some font sizes
See https://dash-docs--181.org.readthedocs.build/en/181/

style: add some custom css

---

_static/css/pydata-overrides.css

@thephez please check if that is the correct way of adding new fonts for this theme. I'm still not that sure its a correct way to adding style things, but hope that's fine. 
First change was to fix the mobile issue with side-bar - the simple fix in removing incorrect code
Second change to add fonts from our website, so I have added to the headers and simple texts
Third change to make a language selector a bit better, this change for both variations - light and dark modes 
Let me please know if there something wrong

con:font-selector-mobile-changes

---

docs/user/mining/index.rst

Reported trojan/botnet embedded in last version

docs: remove unsafe mining software

---

docs/user/wallets/dashcore/advanced.rst
docs/user/wallets/dashcore/cmd-rpc.rst

https://dash-docs--189.org.readthedocs.build/en/189/docs/user/wallets/dashcore/cmd-rpc.html#rpc-commands
https://dash-docs--189.org.readthedocs.build/en/189/docs/user/wallets/dashcore/advanced.html#multiple-wallets

docs: add info about using RPCs with multiple wallets

---

conf.py

chore: bump copyright year to 2023

---

_static/css/pydata-overrides.css

Alternates color on even/odd rows ([example](https://dash-docs--192.org.readthedocs.build/en/192/docs/user/introduction/features.html#block-reward-allocation))

style: minor adjustment to tables

---

docs/user/governance/using.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/advanced.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/electrum/installation.rst
docs/user/wallets/electrum/send-receive.rst
docs/user/wallets/paper.rst
docs/user/wallets/recovery.rst

Preview link: https://dash-docs--207.org.readthedocs.build/en/207/

Image alignment changes.

---

docs/user/wallets/third-party.rst

Preview build: https://dash-docs--224.org.readthedocs.build/en/224/docs/user/wallets/index-third-party.html
Related to #214

Cleaning dead wallets

---

docs/user/dashmate/index.rst
docs/user/index.rst

adding dashmate

---

conf.py

Preview build: https://dash-docs--245.org.readthedocs.build/en/245/

chore: add header link to the forum

---

docs/user/masternodes/setup-hpmn.rst
docs/user/network/dashmate/index.rst

https://dash-docs--246.org.readthedocs.build/en/246/docs/user/masternodes/setup-hpmn.html

docs: start adding dashmate info to HPMN setup

---

conf.py

Will allowing using references to subprojects (https://docs.readthedocs.io/en/stable/guides/intersphinx.html)

feat: add intersphinx extension

---

docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--261.org.readthedocs.build/en/261/

chore: update dashmate deb version

---

docs/user/developers/integration.rst

Preview build: https://dash-docs--264.org.readthedocs.build/en/264/docs/user/developers/integration.html#the-basics

docs: mention IS benefit over normal confs

---

docs/user/masternodes/setup-evonode.rst
locale/ar/LC_MESSAGES/docs/user/introduction/features.po
locale/de/LC_MESSAGES/docs/user/introduction/features.po
locale/el/LC_MESSAGES/docs/user/introduction/features.po
locale/es/LC_MESSAGES/docs/user/introduction/features.po
locale/fr/LC_MESSAGES/docs/user/introduction/features.po
locale/it/LC_MESSAGES/docs/user/introduction/features.po
locale/ja/LC_MESSAGES/docs/user/introduction/features.po
locale/ko/LC_MESSAGES/docs/user/introduction/features.po
locale/pt/LC_MESSAGES/docs/user/introduction/features.po
locale/ru/LC_MESSAGES/docs/user/introduction/features.po
locale/tl/LC_MESSAGES/docs/user/introduction/features.po
locale/vi/LC_MESSAGES/docs/user/introduction/features.po
locale/zh_CN/LC_MESSAGES/docs/user/introduction/features.po
locale/zh_TW/LC_MESSAGES/docs/user/introduction/features.po

Preview build: https://dash-docs--265.org.readthedocs.build/en/265/

HPMN and EVoNode changes

---

docs/user/masternodes/setup-evonode.rst

Fixes this:
Preview build: https://dash-docs--266.org.readthedocs.build/en/266/docs/user/masternodes/setup-evonode.html#manual-installation

fix: correct formatting

---

docs/user/introduction/information.rst

Added coingecko link.
Still need clarity on TG links.
Preview build: https://dash-docs--268.org.readthedocs.build/en/268/

Removed outdated links

---

docs/user/introduction/features.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/understanding.rst
docs/user/network/dashmate/index.rst

We merged the original changes here before the change. This makes it consistent with the docs-core changes.
Preview build: https://dash-docs--273.org.readthedocs.build/en/273/

chore: update capitalization for consistency

---

conf.py

Make "Edit this page" point to Core v19 instead of v18

chore: update conf.py to correction version

---

docs/user/wallets/dashcore/advanced.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst

There was some outdated/missing information related to HD wallets. This cleans up that section and adds some additional info.
Preview build: https://dash-docs--277.org.readthedocs.build/en/277/docs/user/wallets/dashcore/advanced.html#hd-wallets

docs: core HD wallet update

---

docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--284.org.readthedocs.build/en/284/

added payout addresses balance

---

docs/user/network/dashmate/index.rst

Update to latest version of dashmate

chore: update dashmate version

---

docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--286.org.readthedocs.build/en/286/

docs(dashmate): updated to dashmate 0.24.14

---

docs/user/masternodes/setup-evonode.rst
docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--289.org.readthedocs.build/en/289/docs/user/masternodes/setup-evonode.html#server-configuration and https://dash-docs--289.org.readthedocs.build/en/289/docs/user/network/dashmate/index.html#masternode-setup

docs: embed dashmate video tutorial on evonode and dashmate setup pages

---

docs/user/masternodes/understanding.rst

Preview build: https://dash-docs--295.org.readthedocs.build/en/295/

docs: changed stats

---

docs/user/wallets/dashcore/advanced.rst

Preview build: https://dash-docs--297.org.readthedocs.build/en/297/

docs: reorganize HD wallet section

---

docs/user/wallets/dashcore/advanced.rst

Preview build: https://dash-docs--296.org.readthedocs.build/en/296/

docs: add running on testnet subsection

---

index.rst

Includes change that was missed in #300 
Preview build: https://dash-docs--301.org.readthedocs.build/en/301/

docs: update platform link on index

---

transifex/build.sh

Updates script used to trigger translation builds

feat: add webhook to build "it"

---

docs/user/governance/index.rst
docs/user/governance/understanding.rst
docs/user/introduction/features.rst
docs/user/introduction/information.rst
docs/user/masternodes/understanding.rst

Change treasury from 10% to 20%
https://dash-docs--310.org.readthedocs.build/en/310/docs/user/introduction/features.html#block-reward-allocation, etc

docs: update block subsidy split percentages

---

docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--319.org.readthedocs.build/en/319/

docs: update dashmate page

---

_static/js/lang.js

Add some logging to help figure out why some languages aren't working and sync language codes with #317

refactor: language selector update

---

docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst
scripts/update-download-links.sh

Preview build: https://dash-docs--332.org.readthedocs.build/en/332/

chore: update download links for v20.0.4

---

docs/user/wallets/dashcore/installation-windows.rst

Embed Pasta's video overview of Windows binary verification
Preview build: https://dash-docs--338.org.readthedocs.build/en/338/docs/user/wallets/dashcore/installation-windows.html#verifying-dash-core

docs: add windows gpg verification video

---

docs/user/governance/eight-steps.rst
docs/user/governance/index.rst
docs/user/governance/understanding.rst
docs/user/index.rst
docs/user/introduction/about.rst
docs/user/introduction/features.rst
docs/user/introduction/safety.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/understanding.rst
docs/user/network/dashmate/index.rst
docs/user/wallets/dashcore/coinjoin-instantsend.rst
docs/user/wallets/hardware.rst

- Switch youtube embeds to use https and the nocookie youtube site
- Make videos the full width of the content section
Preview build: https://dash-docs--339.org.readthedocs.build/en/339/

chore: misc cleanup

---

docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst
scripts/update-download-links.sh

Merge after actual release
Preview build: https://dash-docs--347.org.readthedocs.build/en/347/

chore: update download links for v20.1.1

---

docs/user/masternodes/hosting.rst

Remove Zaimirai which no longer provides a service
Preview build: https://dash-docs--351.org.readthedocs.build/en/351/

docs: update hosting service list

---

docs/user/introduction/information.rst
docs/user/masternodes/understanding.rst

Preview build: https://dash-docs--358.org.readthedocs.build/en/358/

docs: update mn payment info

---

docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--363.org.readthedocs.build/en/363/

docs: ensure we don't have problems with containers

---

docs/user/masternodes/server-config.rst

Preview build: https://dash-docs--368.org.readthedocs.build/en/368/

docs: add port 80 for ZeroSSL

---

docs/user/masternodes/maintenance.rst
docs/user/masternodes/server-config.rst
docs/user/masternodes/setup.rst
docs/user/network/dashmate/index.rst

Minor updates related to #361 - #364, #367, and #368
Preview build: https://dash-docs--370.org.readthedocs.build/en/370/

docs: misc v21 cleanup

---

docs/user/masternodes/setup-evonode.rst

Preview build: https://dash-docs--365.org.readthedocs.build/en/365/

docs: update dashmate version

---

docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst
scripts/update-download-links.sh

Preview build: https://dash-docs--372.org.readthedocs.build/en/372/

chore: update links to v21.1.0

---

docs/user/developers/sporks.rst
docs/user/introduction/features.rst

Preview build: https://dash-docs--374.org.readthedocs.build/en/374/

docs: update spork info

---

docs/user/masternodes/setup-evonode.rst
docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--376.org.readthedocs.build/en/376/

chore: update dashmate download links for v1.1.0

---

docs/user/masternodes/understanding.rst

Clarify how the reward reallocation affected the frequency and amount of reward payments on the Core chain.
Preview build: https://dash-docs--381.org.readthedocs.build/en/381/docs/user/masternodes/understanding.html#reward-reallocation

docs: expand reward reallocation payment info

---

requirements.txt

Version 2.12 can have an issue building in some time zones
https://dash-docs--386.org.readthedocs.build/en/386/

build: update babel

---

docs/user/network/dashmate/index.rst

we should bring it back later
Preview build: https://dash-docs--388.org.readthedocs.build/en/388/

docs: temporary remove --keep-data

---

docs/user/masternodes/setup-evonode.rst
docs/user/network/dashmate/index.rst

Update download link / install command to the new version. 
**Replace commit hash placeholder "xxxxxxxxx" with the actual build version one before merging**
Preview build: https://dash-docs--385.org.readthedocs.build/en/385/

chore: update dasmate version to v1.2

---

.gitignore
README.md
conf.py

Preview build: https://dash-docs--387.org.readthedocs.build/en/387/

docs: update readme with build instructions

---

docs/user/masternodes/server-config.rst

Related to dashpay/platform#2100 and https://www.dash.org/forum/index.php?threads/dashmate-incorrectly-shows-ports-as-closed.55244/
Preview build: https://dash-docs--390.org.readthedocs.build/en/390/docs/user/masternodes/server-config.html#set-up-your-vps

docs: recommend disabling ipv6

---

docs/user/network/dashmate/index.rst

Preview build: https://dash-docs--392.org.readthedocs.build/en/392/

docs: remove `reset` on update

---

docs/user/masternodes/dashmate-upgrade-v1.rst

Preview build: https://dash-docs--394.org.readthedocs.build/en/394/

docs: remove reset step on updating from v1

---

docs/user/masternodes/dashmate-upgrade-v0_25.rst

Preview build: https://dash-docs--393.org.readthedocs.build/en/393/

docs: do not reset data when upgrade from 0.25

---

scripts/core-download-link-update.sh

Tested in https://github.com/dashpay/docs/actions/runs/11484712591 and https://github.com/dashpay/docs/actions/runs/11484636486

fix: make core version update action work properly

---

.markdownlint.json
conf.py
scripts/dip-format.sh

docs: misc core migration cleanup

---

docs/core/guide/transactions-transaction-fees-and-change.md
docs/user/introduction/features.rst

Clarify MN reward breakdown
Preview build: https://dash-docs--429.org.readthedocs.build/en/429/

docs: misc updates

---

_templates/sidebar-main.html
docs/core/api/remote-procedure-calls-removed.md
docs/core/api/remote-procedure-calls-wallet-deprecated.md
docs/core/index.md
docs/core/reference/p2p-network-control-messages.md
docs/core/reference/p2p-network-deprecated-messages.md

Preview build: https://dash-docs--443.org.readthedocs.build/en/443/

docs: update previous version links

---

.github/workflows/core-download-update.yml
.github/workflows/dashmate-update.yml
.github/workflows/evo-tool-download-update.yml

Use non-default commit message and assign reviewers

ci: update github actions

---

conf.py

So the "Edit on GitHub" link opens the current version

chore: update branch in conf.py

---

docs/user/masternodes/server-config.rst

deleted doubled words
Preview build: https://dash-docs--460.org.readthedocs.build/en/460/

docs(user): Update server-config.rst

---

_static/css/pydata-overrides.css
_static/js/pydata-search-close.js
_templates/sidebar-main.html
conf.py
requirements.txt
transifex/README.md

Updates the Pydata theme and Sphinx along with other dependencies. Performs related updates (config, CSS, etc.) to make everything work with the updated deps.
Preview: https://dash-user-docs.readthedocs.io/en/dependency-update-2024-12-19/

chore: update dependencies to latest release

---

.readthedocs.yml

Preview: https://dash-docs--461.org.readthedocs.build/en/461/

build: update to build with ubuntu 24

---

docs/core/dashcore/wallet-arguments-and-commands-dash-cli.md
docs/core/dashcore/wallet-arguments-and-commands-dash-qt.md
docs/core/dashcore/wallet-arguments-and-commands-dash-tx.md
docs/core/dashcore/wallet-arguments-and-commands-dash-wallet.md
docs/core/dashcore/wallet-arguments-and-commands-dashd.md
scripts/core-help-parsing.sh

Preview build: https://dash-docs--471.org.readthedocs.build/en/471/

docs(core): updated core help for v22

---

docs/user/developers/compiling.rst

Preview build: https://dash-docs--482.org.readthedocs.build/en/482/

chore: bump guix build process xcode version

---

docs/core/api/remote-procedure-call-quick-reference.md
docs/core/api/remote-procedure-calls-blockchain.md
docs/core/api/remote-procedure-calls-control.md
docs/core/api/remote-procedure-calls-dash.md
docs/core/api/remote-procedure-calls-raw-transactions.md
docs/core/api/remote-procedure-calls-wallet.md

Preview build: https://dash-docs--484.org.readthedocs.build/en/484/

docs: v22.1 updates

---

.github/workflows/core-download-update.yml
.github/workflows/evo-tool-download-update.yml

When creating PRs for Core / Evo Tool download link updates, include the new version in the PR title.

ci: add version info to pr title

---

docs/user/wallets/hardware.rst

See https://github.com/sphinx-doc/sphinx/issues/3921#issuecomment-315581557 for details
Preview build: https://dash-docs--502.org.readthedocs.build/en/502/

fix: make ref anonymous to fix warning

---

_extra/llms.txt
conf.py

Initial file based on the concept proposed on https://llmstxt.org/

docs: add llms.txt and update conf.py
