dashpay/docs

developers/index.rst

Preview build @ https://dash-docs--77.org.readthedocs.build/en/77/developers/index.html (issue with webhook config prevented this from showing up automatically in the PR "checks" section - should work for future PRs).

fix: add missing underscore after urls

---

requirements.txt

RTD [recommends](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies) pinning dependency versions to ensure reproducible builds in case an upstream dependency releases a breaking version. This PR pins both dependencies to the current version - verified by checking [build logs](https://readthedocs.org/api/v2/build/13499162.txt) for the most recent build.

build: pin current dependency version

---

introduction/features.rst
wallets/dashcore/privatesend-instantsend.rst

This PR updates the minimum possible number of CoinJoin rounds in the GUI.

fix: incorrect minimum PS rounds

---

developers/insight.rst
masternodes/maintenance.rst
masternodes/setup.rst
mining/p2pool.rst
wallets/dashcore/installation-linux.rst
wallets/dashcore/installation-macos.rst
wallets/dashcore/installation-windows.rst

This PR updates versions in install/update docs to 0.17.0.2

docs: bump version numbers for install docs to 0.17.0.2

---

wallets/dashcore/advanced.rst

Cover the HD upgrade process for those wanting to migrate from a standard wallet. Preview: https://dash-docs--96.org.readthedocs.build/en/96/wallets/dashcore/advanced.html#upgrade-to-hd

docs: add upgrade to HD info for Dash Core

---

developers/compiling.rst

Explains how to setup for gitian builds and use the gitian-build.py script to complete builds.
https://dash-docs--98.org.readthedocs.build/en/98/developers/compiling.html

docs: add gitian build instructions

---

masternodes/setup-testnet.rst

This PR:
- switches the NVM installer from NodeSource to NVM (removes sudo requirement for `npm link`)
- updates the update docs to update dashmate as well as the images it runs

Improve update docs

---

masternodes/setup-testnet.rst

The gist link to get the testnet `genesis.json` was obsolete.

chore: update link to genesis.json gist

---

wallets/dashcore/advanced.rst

The KeePass integration with Core was removed in https://github.com/dashpay/dash/pull/4628. Remove content from docs with message directing to previous version.
Preview at: https://dash-docs--124.org.readthedocs.build/en/124/wallets/dashcore/advanced.html#keepass

docs: remove deprecated KeePass integration details

---

developers/compiling.rst

There may be compatibility issues if attempting to use gitian-build from a different version
Preview: https://dash-docs--136.org.readthedocs.build/en/136/developers/compiling.html#prepare-gitian

docs: use gitian-build from the version being built

---

developers/insight.rst
masternodes/maintenance.rst
masternodes/setup.rst
mining/p2pool.rst
wallets/dashcore/installation-linux.rst
wallets/dashcore/installation-macos.rst
wallets/dashcore/installation-windows.rst

Updates links / executable references to use 18.0.1 instead of 0.17.0.3
Closes #143

chore: update Core 0.17 binary references to 18.0

---

masternodes/maintenance.rst

As requested [on Discord by dashfriend](https://discord.com/channels/484546513507188745/496953691203698703/1011180601342185492). Replaces the shas256 check with the signature check used in https://docs.dash.org/en/stable/masternodes/setup.html#manual-installation.
Preview: https://dash-docs--147.org.readthedocs.build/en/147/masternodes/maintenance.html#manual-update

docs: add authenticity check to MN maintenance

---

masternodes/setup-testnet.rst

Testnet manual setup docs needed a few minor updates:
- Updated `genesis.json`
- Sentinel now supports Python 3.10
- Incorrect folder name after untarring dashcore

chore: update manual install docs for sentinel 1.7 and testnet-12

---

governance/using.rst

Dash Nexus has been unavailable for quite some time. Removes a (dead) link to it.

docs: remove Dash Nexus link

---

developers/insight.rst
masternodes/maintenance.rst
masternodes/setup-testnet.rst
masternodes/setup.rst
mining/p2pool.rst
wallets/dashcore/installation-linux.rst
wallets/dashcore/installation-macos.rst
wallets/dashcore/installation-windows.rst

Update links to point to the current version of Core

chore: update Core 18.0.2 links to 18.1.0

---

conf.py
requirements.txt

This change is to bring us up to the current version of Sphinx (and our current theme). The version we're on currently is about 18 months old and there have been 2 major releases since then. Please click around a bit on the PR build in case some issue shows up on your OS/browser combo that I don't see.
Once we merge this, I will also trigger builds on the translation sites to make sure they continue to operate correctly as well. Not anticipating any issues, but you never know.
PR Build site: https://dash-docs--165.org.readthedocs.build/en/165/

chore: update dependencies

---

.readthedocs.yml

Switch to using Python 3.10. Python 3.7 support ends in ~6 months while 3.10 is good until 2026 (https://endoflife.date/python). Python 3.11 is only a few weeks old so there could be compatibility issues with some extensions at this point.
Also explicitly set which OS is used for the build. Ubuntu 22.04 has been out for >6 mo and will be supported until 2027 (https://wiki.ubuntu.com/Releases) so it seems like a reasonable choice.
PR build: https://dash-docs--166.org.readthedocs.build/en/166/index.html

build: update build settings

---

conf.py
index-network.rst
index-users.rst
index.rst
introduction/index.rst
requirements.txt

Switches site theme to [Pydata](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html). Minor changes related to index files to make the 3 main sections (First Steps, Users, Network) show up in the header instead of all lower-level section links.

style: update to pydata theme

---

masternodes/setup-testnet.rst

This PR removes the `docker-compose` requirement. Docker Compose V1 (Python) has been deprecated and replaced with Docker Compose V2 (Go) which now ships by default with both Docker Desktop and the convenience script we use to install Docker on Linux. This PR can be merged when support for Docker Compose V2 is merged into Dashmate ([dashevo/platform #422](https://github.com/dashevo/platform/pull/422)).

chore: remove use of deprecated docker-compose

---

introduction/information.rst

Reformat existing glossary to introduce the [`glossary` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-glossary). This will later allow referencing defined glossary items using [`:term:` cross-referencing](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-term) feature.
Ultimately this could be used with the [hoverxref plugin](https://sphinx-hoverxref.readthedocs.io/en/latest/usage.html#tooltip-on-glossary-terms) to provide tooltips for glossary terms.
Preview: https://dash-docs--177.org.readthedocs.build/en/177/introduction/information.html#glossary (nothing changes visibly)

chore: reformat glossary and use sphinx glossary directive

---

_templates/sidebar-main.html
conf.py
index.rst

Based on some feedback this adds a custom sidebar page (unfortunately not auto-created) to be shown on the main page. See example here: https://dash-docs--179.org.readthedocs.build/en/179/.

feat: add sidebar to main page with links to all 3 sets of docs

---

_static/js/lang.js
_templates/languages.html

The language selector is currently broken for several languages. There is a difference between how `DOCUMENTATION_OPTIONS['LANGUAGE']` displays these languages (e.g. `zh-CN`) and the actual URL format (e.g. `zh_CN`). At some point in the past (version 0.17.0 of the docs, for example), there wasn't a discrepancy so it's likely that recent updates to sphinx/rtd dependencies broke this. Anyway, this is probably not the prettiest way to fix this, but it works in my testing so that the selector shows the selected language and also allows switching properly to other languages.

fix: language selector fix

---

conf.py
requirements.txt

[myst-parser](https://myst-parser.readthedocs.io/en/latest/index.html) enables markdown support
[hoverxref](https://sphinx-hoverxref.readthedocs.io/en/latest/index.html) enables more advanced options for references

feat: add new extensions

---

docs/user/wallets/dashcore/installation-macos.rst

In cases where there are sequential images and the first one uses the image directive and the second uses the figure directive, the image will be left aligned by default and the figure center aligned. Changing the first one to a figure also makes them align consistently.
Relates to #204 
Preview of fixed image: https://dash-docs--203.org.readthedocs.build/en/203/docs/user/wallets/dashcore/installation-macos.html#running-dash-core-for-the-first-time

style: change image to figure

---

.readthedocs.yml

Reverts dashpay/docs#210 due to PDF build failure causing the entire build to fail

Revert "adding PDF type"

---

docs/user/developers/integration.rst

Pandoc PDF conversion failed because there was a "С" where it looks like a "C" should be :man_facepalming:

fix: replace U+0421 with "C"

---

.github/workflows/preview-url.yml

This PR adds a GitHub Action to automatically append a link to the RTD PR build at the end of the PR description. Tested over here: https://github.com/thephez/dash-user-docs/pull/26. Hopefully it will work the same way here :crossed_fingers:

ci: add preview url to end of PR descriptions

---

docs/user/developers/integration-apis.rst

Chainrider no longer provides a Dash API
Preview build: https://dash-docs--230.org.readthedocs.build/en/230/

chore: remove chainrider

---

docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst

It will be necessary to to use register_prepare_legacy after the v19 hard fork if registering with a "legacy" BLS key
https://dash-docs--234.org.readthedocs.build/en/234/docs/user/masternodes/setup.html#prepare-a-proregtx-transaction

docs: add warning about protx register_prepare_legacy

---

requirements.txt

The latest version of Babel has an issue that causes an error when "make html" is run in some cases. Installing pytz seems to fix it, but this issue makes it seem like that dependency is undesirable: https://github.com/python-babel/babel/issues/716.
Pinning to Babel 2.11.0 for now avoids local build issues.

build: pin Babel version

---

docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst

Update download / command references to use v19 instead of v18
Closes: #193

docs: 19.0.0 binary updates

---

docs/user/masternodes/setup-hpmn.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst

The `masternode outputs` RPC response format changed in the previous release. This updates the docs to show the correct format.

fix: update masternode outputs response format

---

.github/workflows/preview-url.yml

Check if switching to `pull_request_target` will address the issues discussed in #226. Also, only run the action for PRs where doc-related files are modified.

ci: update preview-url action

---

.tx/config
transifex/README.md
transifex/pulltx.sh
transifex/pushtx.sh

Transifex has migrated to V3 of their API and no longer support V2. The existing tool we were using ([transifex-client](https://github.com/transifex/transifex-client)) has been deprecated in favor of a [new CLI client](https://github.com/transifex/cli). This PR updates our scripts, config, and Readme to use that new client (which is still called `tx` - thus the lack of many changes.
I tested this and it seems to all work. I successfully pushed and see the updated files on the Transifex site. I also did a successful pull back out of Transifex. Results of the push can be seen here: https://github.com/thephez/dash-user-docs/pull/29. I think those changes are mainly due to this being the first push in a while and some new pages were added.
Since we keep `master` in sync with the latest …

chore: transifex api migration

---

.gitignore

And when I say "mo" files, I mean ".mo" files, not mo' files. :smile: 
Sphinx will generate them from .po files so they shouldn't be included in the repo

chore: add mo files to gitignore

---

docs/user/wallets/third-party.rst

The [recent hack](https://twitter.com/AtomicWallet/status/1664946301815910400) brought up security concerns so we are removing the wallet from here for now
Preview build: https://dash-docs--275.org.readthedocs.build/en/275/

docs: remove atomic wallet

---

docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst
scripts/update-download-links.sh

Updates download/install related version references for the new Dash Core version. Done using the script added in this PR to make it easily reproducible for future releases.
**Do not merge prior to binary release on https://github.com/dashpay/dash/releases**
Preview build: https://dash-docs--279.org.readthedocs.build/en/279/

chore: 19.2.0 binary updates

---

_static/css/pydata-overrides.css
_static/js/pydata-search-close.js
conf.py
requirements.txt

Replace pydata theme's built-in search with search as you type
Note: for an unknown reason, the PR build doesn't actually have functional search. It can be previewed on this build of the branch itself which does work and is reflective of how it will actually work when merged: 
https://dash-user-docs.readthedocs.io/en/v19-rtd-sphinx-search/?rtd_search=masternode
Current view in light/dark modes:

feat: add readthedocs-sphinx-search

---

docs/user/developers/integration.rst
docs/user/introduction/information.rst

The integration page has had info about InstantSend for quite a while, but nothing about ChainLocks. This PR adds a ChainLocks section with basic info.
Builds on work started in #215 
Preview build: https://dash-docs--290.org.readthedocs.build/en/290/docs/user/developers/integration.html#chainlocks

docs(integration): add chainlocks section info

---

docs/user/introduction/information.rst

Adds explorer proposed on dashpay/docs-core#58
Also removes an explorer that stopped updating blocks 6 yrs ago
Preview build: https://dash-docs--291.org.readthedocs.build/en/291/

docs: add tokenview explorer

---

docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst
scripts/update-download-links.sh

Updates script and download/install related version references for the new Dash Core version. 
Preview build: https://dash-docs--292.org.readthedocs.build/en/292/

chore: Dash Core V19.3.0 binary links

---

docs/user/developers/testnet.rst
docs/user/introduction/features.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst

Core v20 won't require sentinel (dashpay/dash#5525) so we can remove reference to it in setup instructions.
Preview build: https://dash-docs--299.org.readthedocs.build/en/299/

docs: v20 sentinel deprecation

---

_templates/sidebar-main.html
conf.py
docs/user/introduction/information.rst

Switches links from readme.io to docs.dash.org

docs: update platform links in sidebar

---

docs/user/introduction/features.rst
docs/user/introduction/information.rst

In some places a [`U+00A0` character](https://en.wikipedia.org/wiki/Non-breaking_space) was used instead of a typical space. This PR converts them to a typical space character.
Preview build: https://dash-docs--308.org.readthedocs.build/en/308/

docs: remove nonstandard space character

---

docs/user/masternodes/setup-evonode.rst

Users that follows documentation step install incorrect Node.Js version which results in `npm WARN EBADENGINE `
Platform supports Node.Js v18+
Preview build: https://dash-docs--312.org.readthedocs.build/en/312/

Bump nvm install version to Node LTS

---

conf.py
docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst
scripts/update-download-links.sh

Update download / command references to use v20 instead of v19.
Preview build: https://dash-docs--315.org.readthedocs.build/en/315/
(preview link not working due to a webhook migration issue with readthedocs)

chore: update links to v20.0

---

_templates/languages.html

ReadTheDocs update language codes to be normalized as described in https://blog.readthedocs.com/language-codes-are-now-normalized/#language-codes-are-now-normalized

chore: update language codes

---

docs/user/wallets/hardware.rst

Trezor Safe 3 does not support Dash currently.
Preview build: https://dash-docs--325.org.readthedocs.build/en/325/

docs: add note about trezor safe's lack of dash support

---

docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/network/dashmate/index.rst

Bump to the new Node.JS LTS and upgrade NVM install script version
Preview build: https://dash-docs--320.org.readthedocs.build/en/320/

chore: bump node.js and nvm versions

---

docs/user/masternodes/understanding.rst

Revising these again based on input from @splawik21 following the v20 update.
Preview build: https://dash-docs--328.org.readthedocs.build/en/328/docs/user/masternodes/understanding.html#masternode-requirements

docs: update minimum specs

---

docs/user/developers/insight.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-evonode.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
scripts/update-download-links.sh

Preview build: https://dash-docs--330.org.readthedocs.build/en/330/

chore: update download links for v20.0.3

---

docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst

Missed these files in the first PR
Preview build: https://dash-docs--331.org.readthedocs.build/en/331/

chore: update for 20.0.3

---

requirements.txt

To address this vulnerability: https://github.com/readthedocs/readthedocs.org/security/advisories/GHSA-qhqx-5j25-rv48

fix: bump to latest version of sphinx search

---

docs/user/developers/integration.rst

Preview build: https://dash-docs--337.org.readthedocs.build/en/337/docs/user/developers/integration.html

docs: integration docs update

---

transifex/build-status-check.sh
transifex/build.sh
transifex/pulltx.sh
transifex/pushtx.sh

I've been using an alternate shell more recently that isn't bash syntax compatible so it became important to have these set.

chore: set hashbang in scripts

---

_templates/sidebar-main.html
conf.py

Needed to direct to 1.0-dev docs

docs: update links to platform docs to use latest instead of stable

---

docs/user/developers/integration-apis.rst

This site supports Dash-specific QR code generation (creates a code recognizable to Dash wallet).
Preview build: https://dash-docs--352.org.readthedocs.build/en/352/docs/user/developers/integration-apis.html#qr-codes

fix: replace dead qr code generator link with new site

---

docs/user/network/dashmate/index.rst

Don't merge - update with the actual dashmate v1 link which won't be available until it is released on GitHub
Preview build: https://dash-docs--357.org.readthedocs.build/en/357/

chore: placeholder dashmate download link for 1.0.1

---

conf.py
docs/user/masternodes/setup-evonode.rst

Update dashmate download location in another place. Also, change the default docs version so "Edit on GitHub" link directs to the right branch.
Preview build: https://dash-docs--359.org.readthedocs.build/en/359/

chore: release updates

---

docs/user/network/dashmate/index.rst

Add note to clarify that dashmate update cannot be used to install newer versions of dashmate or major version updates
Preview build: https://dash-docs--360.org.readthedocs.build/en/360/

docs: dashmate update note

---

docs/user/masternodes/server-config.rst

- Updated Ubuntu to the latest LTS
- Mentioned that Evonode must have 8GB
- Fixed python package name
Preview build: https://dash-docs--361.org.readthedocs.build/en/361/

docs: update server configuration

---

docs/user/masternodes/maintenance.rst

Preview build: https://dash-docs--364.org.readthedocs.build/en/364/

docs: add proservup for evonode

---

docs/user/masternodes/maintenance.rst

Preview build: https://dash-docs--367.org.readthedocs.build/en/367/

docs: add missing params

---

docs/user/developers/compiling.rst
docs/user/developers/insight.rst
docs/user/developers/integration.rst
docs/user/masternodes/maintenance.rst
docs/user/masternodes/setup-testnet.rst
docs/user/masternodes/setup.rst
docs/user/mining/p2pool.rst
docs/user/wallets/dashcore/installation-linux.rst
docs/user/wallets/dashcore/installation-macos.rst
docs/user/wallets/dashcore/installation-windows.rst
scripts/update-download-links.sh

Preview build: https://dash-docs--371.org.readthedocs.build/en/371/

chore: update links to v21.0.2

---

docs/user/masternodes/dashmate-upgrade-v1.rst

we want to return it back when platform is activated
Preview build: https://dash-docs--379.org.readthedocs.build/en/379/

docs: temporary remove `--keep-data` from v1 upgrade path

---

docs/user/masternodes/dashmate-upgrade-v0_25.rst

we want to return it back when platform is activated
Preview build: https://dash-docs--378.org.readthedocs.build/en/378/

docs: temporary remove `--keep-data` from v0.25 upgrade path

---

docs/user/masternodes/setup-evonode.rst

Preview build: https://dash-docs--380.org.readthedocs.build/en/380/docs/user/masternodes/setup-evonode.html#ssl-certificates

docs: explain SSL certificate chain format

---

docs/user/network/dashmate/index.rst

Info on log setup for Platform services:
Preview build: https://dash-docs--396.org.readthedocs.build/en/396/docs/user/network/dashmate/index.html#configure-platform-logs

docs: dashmate logging for platform services

---

.github/workflows/core-download-update.yml
.github/workflows/dashmate-update.yml

Automatically check if Core or Platform have had releases and open update PRs.
Note: this won't check for an already open PR, so it will probably open 1 per day until one of them is merged.

ci: run core and dashmate update daily

---

docs/user/masternodes/hosting.rst

Crowdnode has changed their fees. They do 20% on Trustless and 35% on Trusted MN/EVOs.
Thanks for noticing @splawik21 :+1: 
Preview build: https://dash-docs--410.org.readthedocs.build/en/410/docs/user/masternodes/hosting.html#crowdnode

docs: update crowdnode fees

---

docs/user/network/dashmate/index.rst

Creates an error during build and transifex processing
Preview build: https://dash-docs--415.org.readthedocs.build/en/415/

docs: fix heading issue

---

.github/workflows/evo-tool-download-update.yml
docs/user/network/dash-evo-tool/index.rst
scripts/evo-tool-download-link-update.sh

Update download links and add a script/GH action to create PRs automatically when new versions are released.
Preview build: https://dash-docs--432.org.readthedocs.build/en/432/

chore: update evo tool download links for 0.4.0

---

docs/user/network/dash-evo-tool/index.rst
docs/user/wallets/dashcore/installation-macos.rst

Preview build: https://dash-docs--430.org.readthedocs.build/en/430/docs/user/network/dash-evo-tool/index.html

docs: add more info about wallets and link to docs

---

docs/user/masternodes/understanding.rst

Evonodes require Haswell architecture at a minimum if using an Intel CPU
Preview build: https://dash-docs--436.org.readthedocs.build/en/436/docs/user/masternodes/understanding.html#evonodes

docs: add note about cpu arch

---

docs/core/api/remote-procedure-calls-raw-transactions.md
docs/core/guide/transactions-transaction-fees-and-change.md
transifex/README.md
transifex/pushtx.sh

They weren't there prior to the integration of Core / User docs. Leaving as-is for now to avoid a massive increase in pages for translation.
Preview build: https://dash-docs--441.org.readthedocs.build/en/441/

build: exclude core docs from transifex for now

---

requirements.txt

Update to v4.0.0
Preview: https://dash-docs--455.org.readthedocs.build/en/455/

chore: update myst-parser to latest version

---

.readthedocs.yml

Update to use Python 3.13 for builds

build: bump to latest supported version of python

---

_templates/sidebar-main.html
docs/core/guide/dash-features-coinjoin.md
docs/core/index.md
docs/user/developers/testnet.rst
docs/user/masternodes/setup-testnet.rst

Testnet insight is now located at https://insight.testnet.networks.dash.org/insight/.
Preview build: https://dash-docs--466.org.readthedocs.build/en/466/

docs: update insight testnet url

---

.github/workflows/core-download-update.yml
.github/workflows/dashmate-update.yml
.github/workflows/evo-tool-download-update.yml

Run every 12 hours to catch releases more quickly

ci: update workflow cron time

---

.readthedocs.yml

Required per https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
Preview: https://dash-docs--472.org.readthedocs.build/en/472/

docs: add explicit config file location

---

scripts/core-download-link-update.sh
scripts/evo-tool-download-link-update.sh

Previously a PR might be created if a value was received but it was "null". Skip those cases now.

ci: don't create pull request if version is null

---

docs/core/reference/p2p-network-data-messages.md

Corrects the `baseBlockHashesNb` data type and removes the limitation not mentioned in the DIP (as noticed by @quantumexplorer)
Preview build: https://dash-docs--488.org.readthedocs.build/en/488/docs/core/reference/p2p-network-data-messages.html#getqrinfo

docs(p2p): correct getqrinfo

---

docs/core/reference/p2p-network-data-messages.md

Align qrinfo in docs with [DIP-24 info](https://github.com/dashpay/dips/blob/master/dip-0024.md#simplified-verification-of-llmqs). Issue reported by @QuantumExplorer 
Preview build: https://dash-docs--489.org.readthedocs.build/en/489/docs/core/reference/p2p-network-data-messages.html#qrinfo

docs(p2p): qrinfo correction

---

docs/user/wallets/electrum/installation.rst

This info was dropped when electrum was not being maintained. Adding it back since it's seeing active development again.
Preview build: https://dash-docs--490.org.readthedocs.build/en/490/docs/user/wallets/electrum/installation.html

docs: add electrum download and install info

---

docs/user/masternodes/setup-evonode.rst

In the [discord](https://discord.com/channels/484546513507188745/496953691203698703/1345262807733501983), a one MNO noticed that certificate bundle name `full_chain.crt`is not correct for dashmate, as dashmate is using `bundle.crt`
Preview build: https://dash-docs--495.org.readthedocs.build/en/495/

docs(core): fixed file name for a certificate bundle

---

docs/core/examples/testing-applications.md
docs/user/developers/testnet.rst

Removed due to Crowdnode shutting down their faucet
Preview build: https://dash-docs--505.org.readthedocs.build/en/505/

chore: remove crowdnode faucet link

---

README.md
docs/user/developers/translating.rst
docs/user/marketing.rst
transifex/README.md

Transifex changed the url format at some point. This PR updates our links to the new format. Closes #508.
Preview build: https://dash-docs--510.org.readthedocs.build/en/510/

docs: fix old transifex links

---

docs/user/wallets/hardware.rst

The site no longer exists.
Closes #517 
Preview build: https://dash-docs--518.org.readthedocs.build/en/518/

docs: remove broken dashnews links
